name: "GitOps IAC"
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main
#       - stage
#     paths:
#       - terraform/**
#   pull_request:
#     branches:
#       - main
#     paths:
#       - terraform/**

env:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}›
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}

jobs:
    terraform:
        name: "Terraform code changes"
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
            working-directory: ./terraform

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
    
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: '1.9.2'

            - name: Terraform Init
              id: terraform_init
              run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

            - name: Terraform Destroy
              run: terraform destroy -auto-approve -input=false -parallelism=1