name: "GitOps IAC"
on:
  push:
    branches:
      - main
      - stage
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

env:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}

jobs:
    terraform:
        name: "Terraform code changes"
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
            working-directory: ./terraform

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
    
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2

            - name: Terraform Init
              id: terraform_init
              run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

            - name: Terraform format
              id: terraform_fmt
              run: terraform fmt -check

            - name: Terraform validate
              id: terraform_validate
              run: terraform validate

            - name: Terraform plan
              id: terraform_plan
              run: terraform plan -out=tfplan
              continue-on-error: true

            - name: Terraform plan output
              if: steps.terraform_plan.outcome == 'failure'
              run: exit 1